license = "All-Rights-Reserved"

[[mods]]
modId = "maple"
version = "${version}"
displayName = "Maple"
iconFile = "assets/maple/icon.png"
authors = "Hardel"
description = '''
Memory optimisation for the server, dedicated or in a singleplayer game.
'''

[[dependencies.maple]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_range}"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "maple.mixins.json"
